version: '3'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    tty: true
    stdin_open: true

    # Command to run Django development server automatically
    command: python api/manage.py runserver 0.0.0.0:8000

    # Command to run Django development server manually (uncomment to use)
    # command: tail -f /dev/null