version: '3'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    tty: true
    stdin_open: true
    depends_on:
      - mongodb
    # command: >
    #   sh -c "python api/mongodb_init.py &&
    #          python api/manage.py runserver 0.0.0.0:8000"

    # Command to run Django development server manually (uncomment to use)
    command: tail -f /dev/null

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: