version: '3'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    tty: true
    stdin_open: true
    depends_on:
      - mongodb
    # Modo de produção (descomentado)
    # command: >
    #   sh -c "python api/manage.py migrate_mongo &&
    #          python api/manage.py runserver 0.0.0.0:8000"

    # Modo de desenvolvimento (comentado)
    # command: >
    #   sh -c "python api/manage.py migrate_mongo && tail -f /dev/null"

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: