version: '3'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"

volumes:
  mongodb_data: